# Ultralytics 🚀 AGPL-3.0 License - https://ultralytics.com/license

blank_issues_enabled: false
contact_links:
  - name: 📄 YOLO Documentation
    url: https://docs.ultralytics.com
    about: Learn how to train, predict, track, and export with Ultralytics YOLO
  - name: 🐛 Ultralytics Package Issues
    url: https://github.com/ultralytics/ultralytics/issues
    about: Report bugs in the ultralytics Python package or yolo CLI
  - name: 💬 Forum
    url: https://community.ultralytics.com
    about: Ask the Ultralytics community for help using YOLO
  - name: 🎧 Discord
    url: https://www.ultralytics.com/discord
    about: Ask on Ultralytics Discord
  - name: ⌨️ Reddit
    url: https://www.reddit.com/r/ultralytics/
    about: Ask on Ultralytics Subreddit
